/**
 * Client-side data export helpers.
 * No external libraries needed - uses native Blob API.
 */

export function exportToCSV<T extends Record<string, unknown>>(
  data: T[],
  filename: string,
  columns?: { key: keyof T; label: string }[]
) {
  if (data.length === 0) return;

  const cols = columns ?? Object.keys(data[0]).map((k) => ({ key: k, label: k }));

  const escape = (val: unknown): string => {
    if (val === null || val === undefined) return "";
    const str = String(val);
    if (str.includes(",") || str.includes('"') || str.includes("\n")) {
      return `"${str.replace(/"/g, '""')}"`;
    }
    return str;
  };

  const header = cols.map((c) => escape(c.label)).join(",");
  const rows = data.map((row) =>
    cols.map((c) => escape(row[c.key as keyof T])).join(",")
  );
  const csv = "\uFEFF" + [header, ...rows].join("\n"); // BOM for Excel UTF-8

  downloadBlob(csv, filename, "text/csv;charset=utf-8");
}

export function exportToJSON(data: unknown, filename: string) {
  const json = JSON.stringify(data, null, 2);
  downloadBlob(json, filename, "application/json");
}

/**
 * Print-to-PDF using browser native print dialog.
 * User can save as PDF from the print dialog.
 */
export function printPDF(htmlContent: string, title = "Report") {
  const printWindow = window.open("", "_blank", "width=900,height=700");
  if (!printWindow) {
    alert("Pop-up blocked. Please allow pop-ups to export PDF.");
    return;
  }

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title}</title>
        <meta charset="utf-8">
        <style>
          * { box-sizing: border-box; }
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            margin: 0;
            padding: 32px;
            color: #0f172a;
            font-size: 12px;
          }
          h1 { font-size: 22px; margin: 0 0 6px; }
          h2 { font-size: 16px; margin: 24px 0 12px; color: #1e3a8a; }
          .header { border-bottom: 2px solid #2563eb; padding-bottom: 16px; margin-bottom: 24px; }
          .meta { color: #64748b; font-size: 11px; }
          table { width: 100%; border-collapse: collapse; margin: 12px 0; }
          th, td { padding: 8px 10px; text-align: left; border-bottom: 1px solid #e2e8f0; }
          th { background: #f1f5f9; font-weight: 600; font-size: 11px; text-transform: uppercase; color: #475569; }
          tr:nth-child(even) td { background: #fafbfc; }
          .stat-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin: 16px 0; }
          .stat-card { border: 1px solid #e2e8f0; border-radius: 8px; padding: 12px; }
          .stat-label { color: #64748b; font-size: 10px; text-transform: uppercase; }
          .stat-value { font-size: 20px; font-weight: 700; margin-top: 4px; }
          .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 10px; text-align: center; }
          @media print {
            body { padding: 16px; }
            .no-print { display: none; }
          }
        </style>
      </head>
      <body>
        ${htmlContent}
        <div class="footer">
          Generated by LaundryHub · ${new Date().toLocaleString("id-ID")}
        </div>
        <script>
          window.onload = () => {
            setTimeout(() => window.print(), 300);
          };
        </script>
      </body>
    </html>
  `);
  printWindow.document.close();
}

export function formatTableHTML<T>(
  data: T[],
  columns: { key: keyof T; label: string; format?: (v: unknown) => string }[]
): string {
  const headers = columns.map((c) => `<th>${c.label}</th>`).join("");
  const rows = data
    .map((row) => {
      const cells = columns
        .map((c) => {
          const val = row[c.key as keyof T];
          const formatted = c.format ? c.format(val) : String(val ?? "");
          return `<td>${formatted}</td>`;
        })
        .join("");
      return `<tr>${cells}</tr>`;
    })
    .join("");
  return `<table><thead><tr>${headers}</tr></thead><tbody>${rows}</tbody></table>`;
}

function downloadBlob(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 100);
}
